import { useState, type FormEvent } from "react";
import { useGame } from "../context/GameContext";
import { ConnectionBadge } from "../components/ConnectionBadge";

const query = new URLSearchParams(window.location.search);
const pathCode = window.location.pathname.match(/^\/room\/([A-Za-z0-9]{6})\/?$/)?.[1]?.toUpperCase() ?? query.get("room")?.toUpperCase() ?? "";
const platformNickname = query.get("platformNickname")?.trim().slice(0, 16) ?? "";
export function HomePage() {
  const { createRoom, joinRoom, connected } = useGame(); const [nickname, setNickname] = useState(platformNickname); const [roomCode, setRoomCode] = useState(pathCode); const [busy, setBusy] = useState(false);
  const act = async (mode: "create" | "join") => { if (nickname.trim().length < 2) return; setBusy(true); try { await (mode === "create" ? createRoom(nickname) : joinRoom(nickname, roomCode)); } finally { setBusy(false); } };
  const submit = (event: FormEvent) => { event.preventDefault(); void act(pathCode ? "join" : "create"); };
  return <main className="home-shell"><header className="brand-bar"><a className="brand" href="/"><span className="brand-sigil">M</span><span>흑야 저택<small>MYSTERY MANOR</small></span></a><ConnectionBadge /></header><section className="case-intro"><div className="case-file"><span className="case-index">CASE // 001</span><h1>봉인된 밤의<br/><em>사건 기록</em></h1><p>저택에 남은 단서는 세 가지. 누가, 어디서, 무엇을 사용했는지 다른 조사관보다 먼저 밝혀내세요.</p><div className="clue-line"><span>용의자 6</span><i/><span>장소 9</span><i/><span>도구 6</span></div></div><form className="entry-card" onSubmit={submit}><span className="eyebrow">조사 등록</span><h2>{pathCode ? `${pathCode} 방 참가` : "사건에 합류하기"}</h2>{platformNickname ? <p className="form-hint">플랫폼 닉네임 <b>{platformNickname}</b>으로 입장합니다.</p> : <label>조사관 이름<input value={nickname} onChange={(event) => setNickname(event.target.value)} minLength={2} maxLength={16} placeholder="닉네임 2~16자" autoFocus /></label>}{!pathCode && <label>방 코드<input className="code-input" value={roomCode} onChange={(event) => setRoomCode(event.target.value.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 6))} maxLength={6} placeholder="6자리 코드" /></label>}<div className="entry-actions">{pathCode ? <button className="primary-button" disabled={busy || !connected || nickname.trim().length < 2}>초대받은 방 참가</button> : <><button type="button" className="primary-button" onClick={() => void act("create")} disabled={busy || !connected || nickname.trim().length < 2}>새 조사실 만들기</button><button type="button" className="secondary-button" onClick={() => void act("join")} disabled={busy || !connected || nickname.trim().length < 2 || roomCode.length !== 6}>코드로 참가</button></>}</div><small className="form-hint">게임은 3~6명이 함께 진행합니다.</small></form></section><footer className="home-footer"><span>ORIGINAL PROTOTYPE · NO THIRD-PARTY ASSETS</span><span>PC / MOBILE · REAL-TIME</span></footer></main>;
}
